//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Question
    {
        [DataMember]
        public int QuestionId { get; set; }
        [DataMember]
        public Nullable<int> SubjectId { get; set; }
        [DataMember]
        public Nullable<int> LevelId { get; set; }
        [DataMember]
        public string Question1 { get; set; }
        [DataMember]
        public string Option1 { get; set; }
        [DataMember]
        public string Option2 { get; set; }
        [DataMember]
        public string Option3 { get; set; }
        [DataMember]
        public string Option4 { get; set; }
        [DataMember]
        public Nullable<int> Answer { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
